/* =========================================
   data.js
   - 효빈광역시 공식 홈페이지 다국어 텍스트 및 검색 인덱스
   ========================================= */

// 1. 다국어 텍스트 정의
const translations = {
    'ko': {
        'city-name': '효빈광역시',
        'ribbon-slogan': '모두의 밝은 미래, 함께하는 효빈광역시.',
        'main-slogan-pre': '시민이 행복한 도시로!',
        'main-slogan-main': '효빈시장 박효빈입니다.',
        'mascot-title-pre': '효빈광역시',
        'mascot-title': '마스코트 캐릭터',
        'mascot-name': '한바다',
        'search-placeholder': '검색',
        'menu-civil': '민원',
        'menu-news': '시정소식',
        'menu-life': '생활정보',
        'menu-transport': '교통',
        'menu-welfare': '복지',
        'menu-job': '일자리',
        'menu-tour': '관광',
        'menu-notice': '공지사항',
        'menu-contact': '문의',
        'menu-search-district': '행정구역 검색',
        'board-news': '새소식',
        'board-construction': '공사알림',
        'board-notice': '고시&공고',
        'board-recruit': '시험채용',
        'board-press': '보도자료',
        'board-sister-cities': '자매결연도시',
        'dept-traffic-welfare': '교통복지과',
        'dept-culture-industry': '문화산업과',
        'dept-youth-policy': '청년정책과',
        'dept-bus-policy': '버스정책과',
        'post-title-1': '2026 취약계층 교통비 지원사업 최종 계획안 공개',
        'post-content-1': '교통복지과는 내년부터 시행될 새로운 지원사업의 세부 내용을 공개하고 시민들의 의견을 적극 수렴하여 최종안을 확정지을 예정입니다.',
        'post-title-2': '2026 HAF (Hyobin Animation Festival) 최종 계획안 공개',
        'post-title-3': '2026년 청년 정책참여 프로그램 참여자 모집 계획안 공개',
        'post-title-4': '겨울철 폭설 대비 시내버스 노선 우회 계획 공지',
        'banner-safety-title': '시민안전보험',
        'banner-safety-content': '예기치 못한 사고, 효빈시가 든든하게 지켜드립니다. 자동 가입 혜택 안내.',
        'banner-learning-title': '평생학습 수강생 모집',
        'banner-learning-content': '2025년 상반기 시민 교양 강좌 수강생을 모집합니다. 배움의 기쁨을 누리세요.',
        'banner-tour-title': '효빈 시티투어',
        'banner-tour-content': '도심의 명소부터 숨겨진 성지까지! 2층 버스로 떠나는 여행.',
        'footer-privacy': '개인정보처리방침',
        'footer-copyright': '저작권정책',
        'footer-cctv': '영상정보처리기기 운영방침',
        'footer-viewer': '뷰어내려받기',
        'footer-error': '누리집 오류신고',
        'footer-directions': '오시는 길',
        'footer-zip': '(우) 79791',
        'footer-address': '효빈광역시 북구 효빈로 79(고송8동)',
        'footer-tel-label': '대표전화',
        'footer-tel-number': '079-591-2548',
        'footer-tel-hours': '월~금 : 08:30~18:30 (시간외는 당직실로 연결)',
        'footer-fax-label': '팩스',
        'footer-fax-number': '079-591-2547',
        'footer-duty-label': '당직실',
        'footer-duty-number': '079-591-2546',
        'footer-duty-hours': '(야간, 공휴일)'
    },
    'en': {
        'city-name': 'Hyobin Metropolitan City',
        'ribbon-slogan': 'A bright future for everyone, Hyobin Metropolitan City together.',
        'main-slogan-pre': 'A city where citizens are happy!',
        'main-slogan-main': 'I am Hyobin Park, Mayor of Hyobin.',
        'mascot-title-pre': 'Hyobin Metropolitan City',
        'mascot-title': 'Mascot Character',
        'mascot-name': 'Hanbada',
        'search-placeholder': 'Search',
        'menu-civil': 'Civil Petitions',
        'menu-news': 'City News',
        'menu-life': 'Living Info',
        'menu-transport': 'Transportation',
        'menu-welfare': 'Welfare',
        'menu-job': 'Jobs',
        'menu-tour': 'Tourism',
        'menu-notice': 'Notices',
        'menu-contact': 'Inquiry',
        'menu-search-district': 'Search District',
        'board-news': 'New Notices',
        'board-construction': 'Construction Alerts',
        'board-notice': 'Official Notices',
        'board-recruit': 'Recruitment',
        'board-press': 'Press Releases',
        'board-sister-cities': 'Sister Cities',
        'dept-traffic-welfare': 'Traffic Welfare Dept.',
        'dept-culture-industry': 'Culture Industry Dept.',
        'dept-youth-policy': 'Youth Policy Dept.',
        'dept-bus-policy': 'Bus Policy Dept.',
        'post-title-1': 'Final plan for 2026 vulnerable transportation support announced',
        'post-content-1': 'The Traffic Welfare Division will announce the detailed contents of the new support project to be implemented starting next year and will finalize the plan after actively gathering citizen opinions.',
        'post-title-2': 'Final Plan for 2026 HAF (Hyobin Animation Festival) Released',
        'post-title-3': '2026 Youth Policy Participation Program Participant Recruitment Plan Announced',
        'post-title-4': 'Notice on bus route detours in preparation for heavy snow in winter',
        'banner-safety-title': 'Citizen Safety Insurance',
        'banner-safety-content': 'In case of unexpected accidents, Hyobin City will reliably protect you. Automatic subscription benefits guide.',
        'banner-learning-title': 'Recruiting Lifelong Learning Students',
        'banner-learning-content': 'Recruiting students for the first half of 2025 citizen liberal arts courses. Enjoy the joy of learning.',
        'banner-tour-title': 'Hyobin City Tour',
        'banner-tour-content': 'From downtown landmarks to hidden sanctuaries! A trip on a double-decker bus.',
        'footer-privacy': 'Privacy Policy',
        'footer-copyright': 'Copyright Policy',
        'footer-cctv': 'CCTV Policy',
        'footer-viewer': 'Viewer Download',
        'footer-error': 'Website Error Report',
        'footer-directions': 'Directions',
        'footer-zip': 'Zip Code 79791',
        'footer-address': '79 Hyobin-ro, Buk-gu, Hyobin Metropolitan City (Gosong 8-dong)',
        'footer-tel-label': 'Main Tel',
        'footer-tel-number': '079-591-2548',
        'footer-tel-hours': 'Mon-Fri: 08:30~18:30 (After hours connect to Duty Room)',
        'footer-fax-label': 'Fax',
        'footer-fax-number': '079-591-2547',
        'footer-duty-label': 'Duty Room',
        'footer-duty-number': '079-591-2546',
        'footer-duty-hours': '(Night, Holidays)'
    },
    'zh': {
        'city-name': '孝彬廣域市',
        'ribbon-slogan': '共同的燦爛未來，攜手共進的孝彬廣域市。',
        'main-slogan-pre': '讓市民幸福的城市!',
        'main-slogan-main': '我是孝彬市長朴孝彬。',
        'mascot-title-pre': '孝彬廣域市',
        'mascot-title': '吉祥物角色',
        'mascot-name': '韓巴達',
        'search-placeholder': '搜索',
        'menu-civil': '民願',
        'menu-news': '市政消息',
        'menu-life': '生活情報',
        'menu-transport': '交通',
        'menu-welfare': '福祉',
        'menu-job': '工作',
        'menu-tour': '觀光',
        'menu-notice': '公示事項',
        'menu-contact': '諮詢',
        'menu-search-district': '行政區域搜索',
        'board-news': '最新消息',
        'board-construction': '施工通知',
        'board-notice': '告示&公告',
        'board-recruit': '考試招聘',
        'board-press': '報道資料',
        'board-sister-cities': '姊妹結緣城市',
        'dept-traffic-welfare': '交通福祉課',
        'dept-culture-industry': '文化産業課',
        'dept-youth-policy': '青年政策課',
        'dept-bus-policy': '公交政策課',
        'post-title-1': '2026年弱勢羣體交通費支援項目最終方案公佈',
        'post-content-1': '交通福利科將公佈明年實施的新支援項目的詳細內容，並積極收集市民意見後確定最終方案。',
        'post-title-2': '2026 HAF (孝彬動畫節) 最終計劃案公佈',
        'post-title-3': '2026年青年政策參與計劃參與者招募計劃公佈',
        'post-title-4': '冬季暴雪 대비 市內公交路綫繞行計劃公示',
        'banner-safety-title': '市民安全保險',
        'banner-safety-content': '對於意外事故，孝彬市提供可靠保障。自動加入優惠指南。',
        'banner-learning-title': '招募終身學習學員',
        'banner-learning-content': '招募2025年上半年市民教養講座學員。享受學習的樂趣。',
        'banner-tour-title': '孝彬城市旅遊',
        'banner-tour-content': '從市中心名勝到隱藏的聖地! 乘坐雙層巴士的旅行。',
        'footer-privacy': '個人信息處理方針',
        'footer-copyright': '版權政策',
        'footer-cctv': '影像信息處理器運營方針',
        'footer-viewer': '瀏覽器下載',
        'footer-error': '網站錯誤申告',
        'footer-directions': '來訪路線',
        'footer-zip': '郵編 79791',
        'footer-address': '孝彬廣域市 北區 孝彬路 79(高松8洞)',
        'footer-tel-label': '代表電話',
        'footer-tel-number': '079-591-2548',
        'footer-tel-hours': '週一至週五: 08:30~18:30 (時間外轉接值班室)',
        'footer-fax-label': '傳真',
        'footer-fax-number': '079-591-2547',
        'footer-duty-label': '值班室',
        'footer-duty-number': '079-591-2546',
        'footer-duty-hours': '(夜間, 節假日)'
    },
    'ja': {
        'city-name': '孝彬広域市',
        'ribbon-slogan': 'みんなの明るい未来、共にする孝彬広域市。',
        'main-slogan-pre': '市民が幸せな都市へ!',
        'main-slogan-main': '孝彬市長の朴孝彬です。',
        'mascot-title-pre': '孝彬広域市',
        'mascot-title': 'マスコットキャラクター',
        'mascot-name': 'ハンバダ',
        'search-placeholder': '検索',
        'menu-civil': '請願',
        'menu-news': '市政ニュース',
        'menu-life': '生活情報',
        'menu-transport': '交通',
        'menu-welfare': '福祉',
        'menu-job': '仕事',
        'menu-tour': '観光',
        'menu-notice': 'お知らせ',
        'menu-contact': 'お問い合わせ',
        'menu-search-district': '行政区域検索',
        'board-news': '新着情報',
        'board-construction': '工事のお知らせ',
        'board-notice': '告示・公告',
        'board-recruit': '採用試験',
        'board-press': '報道資料',
        'board-sister-cities': '姉妹提携都市',
        'dept-traffic-welfare': '交通福祉課',
        'dept-culture-industry': '文化産業課',
        'dept-youth-policy': '青年政策課',
        'dept-bus-policy': 'バス政策課',
        'post-title-1': '2026年 脆弱階層の交通費支援事業最終計画案を公開',
        'post-content-1': '交通福祉課は来年から施行される新規支援事業の詳細を公開し、市民の意見を積極的に収集して最終案を確定する予定です。',
        'post-title-2': '2026 HAF (孝彬アニメーションフェスティバル) 最終計画案公開',
        'post-title-3': '2026年 青年政策参加プログラム参加者募集計画案公開',
        'post-title-4': '冬季の降雪に備えた市内バス路線迂回計画の公示',
        'banner-safety-title': '市民安全保険',
        'banner-safety-content': '予期せぬ事故、孝彬市が心強くお守りします。自動加入特典のご案内。',
        'banner-learning-title': '生涯学習受講生募集',
        'banner-learning-content': '2025年上半期市民教養講座の受講生を募集します。学びの喜びを享受してください。',
        'banner-tour-title': '孝彬シティツアー',
        'banner-tour-content': '都心の名所から隠れた聖地まで! 2階建てバスで行く旅行。',
        'footer-privacy': '個人情報保護方針',
        'footer-copyright': '著作権ポリシー',
        'footer-cctv': '映像情報処理機器運用方針',
        'footer-viewer': 'ビューアダウンロード',
        'footer-error': 'ウェブサイトエラー報告',
        'footer-directions': 'アクセス',
        'footer-zip': '郵便番号 79791',
        'footer-address': '孝彬広域市 北区 孝彬路 79(古松8洞)',
        'footer-tel-label': '代表電話',
        'footer-tel-number': '079-591-2548',
        'footer-tel-hours': '月～金: 08:30～18:30 (時間外は当直室へ転送)',
        'footer-fax-label': 'FAX',
        'footer-fax-number': '079-591-2547',
        'footer-duty-label': '当直室',
        'footer-duty-number': '079-591-2546',
        'footer-duty-hours': '(夜間、祝日)'
    },
    'tl': {
        'city-name': 'Lungsod ng Hyobin',
        'ribbon-slogan': 'Isang maliwanag na hinaharap para sa lahat, Hyobin Metropolitan City na magkasama.',
        'main-slogan-pre': 'Isang lungsod kung saan masaya ang mga mamamayan!',
        'main-slogan-main': 'Ako si Hyobin Park, Alkalde ng Hyobin.',
        'mascot-title-pre': 'Lungsod ng Hyobin',
        'mascot-title': 'Karakter ng Maskot',
        'mascot-name': 'Hanbada',
        'search-placeholder': 'Maghanap',
        'menu-civil': 'Petisyon',
        'menu-news': 'Balita ng Lungsod',
        'menu-life': 'Impormasyon sa Buhay',
        'menu-transport': 'Transportasyon',
        'menu-welfare': 'Kagalingan',
        'menu-job': 'Trabaho',
        'menu-tour': 'Turismo',
        'menu-notice': 'Paunawa',
        'menu-contact': 'Pagtatanong',
        'menu-search-district': 'Maghanap ng Distrito',
        'board-news': 'Bagong Balita',
        'board-construction': 'Mga Alerto sa Konstruksiyon',
        'board-notice': 'Mga Opisyal na Paunawa',
        'board-recruit': 'Pagre-recruit',
        'board-press': 'Mga Pahayag sa Media',
        'board-sister-cities': 'Mga Kapatid na Lungsod',
        'dept-traffic-welfare': 'Tanggapan ng Traffic Welfare',
        'dept-culture-industry': 'Tanggapan ng Industriya ng Kultura',
        'dept-youth-policy': 'Tanggapan ng Patakaran sa Kabataan',
        'dept-bus-policy': 'Tanggapan ng Patakaran sa Bus',
        'post-title-1': 'Huling plano para sa 2026 suporta sa transportasyon para sa mahihina inihayag',
        'post-content-1': 'Ang Traffic Welfare Division ay mag-aanunsyo ng detalyadong nilalaman ng bagong proyekto ng suporta na ipapatupad simula sa susunod na taon at pinal na isasapinal ang plano matapos aktibong mangalap ng opinyon ng mamamayan.',
        'post-title-2': 'Huling Plano para sa 2026 HAF (Hyobin Animation Festival) Inilabas',
        'post-title-3': '2026 Patakaran sa Kabataan Programa ng Pakikilahok Plano ng Pagre-recruit Inihayag',
        'post-title-4': 'Paunawa tungkol sa paglihis ng ruta ng bus ng lungsod bilang paghahanda para sa malakas na niyebe sa taglamig',
        'banner-safety-title': 'Seguro sa Kaligtasan ng Mamamayan',
        'banner-safety-content': 'Sa kaso ng hindi inaasahang aksidente, maaasahang protektahan ka ng Lungsod ng Hyobin. Gabay sa awtomatikong mga benepisyo sa subscription.',
        'banner-learning-title': 'Nagre-recruit ng mga Estudyante sa Lifelong Learning',
        'banner-learning-content': 'Nagre-recruit ng mga mag-aaral para sa mga kurso sa sining ng mamamayan sa unang kalahati ng 2025. I-enjoy ang saya ng pag-aaral.',
        'banner-tour-title': 'Hyobin City Tour',
        'banner-tour-content': 'Mula sa mga palatandaan sa downtown hanggang sa mga nakatagong santuwaryo! Isang paglalakbay sa isang double-decker bus.',
        'footer-privacy': 'Patakaran sa Privacy',
        'footer-copyright': 'Patakaran sa Copyright',
        'footer-cctv': 'Patakaran sa CCTV',
        'footer-viewer': 'I-download ang Viewer',
        'footer-error': 'Mag-ulat ng Error sa Website',
        'footer-directions': 'Direksyon',
        'footer-zip': 'Zip Code 79791',
        'footer-address': '79 Hyobin-ro, Buk-gu, Hyobin Metropolitan City (Gosong 8-dong)',
        'footer-tel-label': 'Pangunahing Telepono',
        'footer-tel-number': '079-591-2548',
        'footer-tel-hours': 'Lunes-Biyernes: 08:30~18:30 (Pagkatapos의 시간은 당직실로 연결)',
        'footer-fax-label': 'Fax',
        'footer-fax-number': '079-591-2547',
        'footer-duty-label': 'Duty Room',
        'footer-duty-number': '079-591-2546',
        'footer-duty-hours': '(Gabi, Piyesta Opisyal)'
    }
};

// 2. 검색 대상 데이터(페이지/게시물/서비스) 샘플
const SEARCH_INDEX = [
  // 메인 게시물/새소식
  {
    id: "news_traffic_support",
    type: "새소식",
    title: "2026 취약계층 교통비 지원사업 최종 계획안 공개",
    dept: "교통복지과",
    date: "2025-11-28",
    tags: ["교통", "복지", "지원", "취약계층", "교통비"],
    url: "news_traffic_support.html",
    summary: "내년부터 시행될 새로운 지원사업의 세부 내용을 공개하고 시민 의견을 수렴합니다."
  },
  {
    id: "news_haf_2026",
    type: "새소식",
    title: "2026 HAF (Hyobin Animation Festival) 최종 계획안 공개",
    dept: "문화산업과",
    date: "2025-11-28",
    tags: ["애니메이션", "축제", "HAF", "문화", "행사"],
    url: "news_haf_2026.html",
    summary: "2026 HAF 행사 개요, 프로그램 구성, 일정(안)을 안내합니다."
  },
  {
    id: "news_youth_policy",
    type: "새소식",
    title: "2026년 청년 정책참여 프로그램 참여자 모집 계획안 공개",
    dept: "청년정책과",
    date: "2025-11-27",
    tags: ["청년", "참여", "정책", "모집"],
    url: "news_youth_policy.html",
    summary: "청년 정책참여 프로그램의 모집 절차 및 일정(안)을 안내합니다."
  },
  {
    id: "news_winter_bus",
    type: "새소식",
    title: "겨울철 폭설 대비 시내버스 노선 우회 계획 공지",
    dept: "버스정책과",
    date: "2025-11-27",
    tags: ["버스", "폭설", "우회", "노선", "교통"],
    url: "news_winter_bus.html",
    summary: "폭설 시 안전을 위한 임시 우회 노선을 안내합니다."
  },

  // 주요 서비스/페이지
  { id:"civil", type:"메뉴", title:"민원", dept:"", date:"", tags:["민원","신청","제증명"], url:"civil.html", summary:"온라인 민원 및 신고/신청 안내" },
  { id:"news", type:"메뉴", title:"시정소식", dept:"", date:"", tags:["뉴스","소식","보도자료"], url:"news.html", summary:"효빈광역시 시정 뉴스/공지 모음" },
  { id:"life", type:"메뉴", title:"생활정보", dept:"", date:"", tags:["생활","편의","정보"], url:"life.html", summary:"생활/편의 정보 안내" },
  { id:"transport", type:"메뉴", title:"교통", dept:"", date:"", tags:["교통","버스","도시철도"], url:"transport.html", summary:"버스/철도/교통정책 안내" },
  { id:"welfare", type:"메뉴", title:"복지", dept:"", date:"", tags:["복지","지원","혜택"], url:"welfare.html", summary:"복지 서비스 안내" },
  { id:"job", type:"메뉴", title:"일자리", dept:"", date:"", tags:["일자리","채용","취업"], url:"job.html", summary:"일자리/채용/취업 지원" },
  { id:"tour", type:"메뉴", title:"관광", dept:"", date:"", tags:["관광","여행","시티투어"], url:"tour.html", summary:"효빈 관광/시티투어 안내" },
  { id:"notice", type:"메뉴", title:"공지사항", dept:"", date:"", tags:["공지","알림"], url:"notice.html", summary:"공지사항 모음" },

  // 아이콘 메뉴
  { id:"city_hall", type:"서비스", title:"청사안내", dept:"", date:"", tags:["청사","안내","오시는길"], url:"city_hall.html", summary:"청사 위치 및 시설 안내" },
  { id:"subway", type:"서비스", title:"도시철도", dept:"", date:"", tags:["지하철","노선","역"], url:"subway.html", summary:"도시철도 노선/운행 정보" },
  { id:"culture", type:"서비스", title:"문화&행사", dept:"", date:"", tags:["문화","행사","축제"], url:"culture.html", summary:"문화행사/축제 정보" },
  { id:"economy", type:"서비스", title:"금융관련", dept:"", date:"", tags:["금융","지원","경제"], url:"economy.html", summary:"금융/경제 관련 안내" },
  { id:"bus", type:"서비스", title:"버스", dept:"", date:"", tags:["버스","노선","정류장"], url:"bus.html", summary:"버스 노선/시간표 안내" },
  { id:"petition", type:"서비스", title:"시장에게 바란다", dept:"", date:"", tags:["건의","제안","참여"], url:"petition.html", summary:"시민 건의/제안 접수" },
  { id:"org", type:"서비스", title:"조직도", dept:"", date:"", tags:["조직","부서","전화"], url:"org.html", summary:"조직/부서 안내" },

  // 참여/소통
  { id:"data", type:"서비스", title:"공공데이터", dept:"", date:"", tags:["데이터","API","공개"], url:"data.html", summary:"공공데이터 개방 안내" },
  { id:"vr", type:"서비스", title:"VR투어", dept:"", date:"", tags:["VR","투어","체험"], url:"vr.html", summary:"VR로 둘러보는 효빈" },
  { id:"history", type:"서비스", title:"역사관", dept:"", date:"", tags:["역사","기록","전시"], url:"history.html", summary:"효빈 역사관 안내" }
];